// Vocabulary and conversation data for the Spanish travel-practice app.
// Sourced from vocabulary-lists.md — keep the two in sync when adding themes.

const THEMES = [
  {
    id: "greetings",
    title: "Greetings & Introductions",
    items: [
      { es: "hola", en: "hello", pron: "OH-lah" },
      { es: "adiós", en: "goodbye", pron: "ah-DYOHS" },
      { es: "buenos días", en: "good morning", pron: "BWEH-nos DEE-as" },
      { es: "buenas tardes", en: "good afternoon", pron: "BWEH-nas TAR-des" },
      { es: "buenas noches", en: "good evening / good night", pron: "BWEH-nas NOH-ches" },
      { es: "¿Cómo estás?", en: "How are you? (informal)", pron: "KOH-moh es-TAHS" },
      { es: "bien, gracias", en: "fine, thank you", pron: "byen GRAH-syahs" },
      { es: "me llamo…", en: "my name is…", pron: "meh YAH-moh" },
      { es: "mucho gusto", en: "nice to meet you", pron: "MOO-choh GOOS-toh" },
      { es: "¿Cómo te llamas?", en: "What's your name? (informal)", pron: "KOH-moh teh YAH-mahs" },
      { es: "por favor", en: "please", pron: "por fah-VOR" },
      { es: "gracias", en: "thank you", pron: "GRAH-syahs" },
    ],
  },
  {
    id: "numbers",
    title: "Numbers 1–20",
    items: [
      { es: "uno", en: "one", pron: "OO-noh" },
      { es: "dos", en: "two", pron: "dohs" },
      { es: "tres", en: "three", pron: "tres" },
      { es: "cuatro", en: "four", pron: "KWAH-troh" },
      { es: "cinco", en: "five", pron: "SEEN-koh" },
      { es: "seis", en: "six", pron: "says" },
      { es: "siete", en: "seven", pron: "SYEH-teh" },
      { es: "ocho", en: "eight", pron: "OH-choh" },
      { es: "nueve", en: "nine", pron: "NWEH-veh" },
      { es: "diez", en: "ten", pron: "dyes" },
      { es: "once", en: "eleven", pron: "ON-seh" },
      { es: "doce", en: "twelve", pron: "DOH-seh" },
      { es: "trece", en: "thirteen", pron: "TREH-seh" },
      { es: "catorce", en: "fourteen", pron: "kah-TOR-seh" },
      { es: "quince", en: "fifteen", pron: "KEEN-seh" },
      { es: "dieciséis", en: "sixteen", pron: "dyeh-see-SAYS" },
      { es: "diecisiete", en: "seventeen", pron: "dyeh-see-SYEH-teh" },
      { es: "dieciocho", en: "eighteen", pron: "dyeh-see-OH-choh" },
      { es: "diecinueve", en: "nineteen", pron: "dyeh-see-NWEH-veh" },
      { es: "veinte", en: "twenty", pron: "BAYN-teh" },
    ],
  },
  {
    id: "colors-days-time",
    title: "Colors, Days & Time",
    items: [
      { es: "rojo", en: "red", pron: "ROH-hoh" },
      { es: "azul", en: "blue", pron: "ah-SOOL" },
      { es: "verde", en: "green", pron: "VER-deh" },
      { es: "amarillo", en: "yellow", pron: "ah-mah-REE-yoh" },
      { es: "negro", en: "black", pron: "NEH-groh" },
      { es: "blanco", en: "white", pron: "BLAN-koh" },
      { es: "gris", en: "gray", pron: "grees" },
      { es: "naranja", en: "orange", pron: "nah-RAN-hah" },
      { es: "lunes", en: "Monday", pron: "LOO-nes" },
      { es: "martes", en: "Tuesday", pron: "MAR-tes" },
      { es: "miércoles", en: "Wednesday", pron: "MYER-koh-les" },
      { es: "jueves", en: "Thursday", pron: "HWEH-ves" },
      { es: "viernes", en: "Friday", pron: "VYER-nes" },
      { es: "sábado", en: "Saturday", pron: "SAH-bah-doh" },
      { es: "domingo", en: "Sunday", pron: "doh-MEEN-goh" },
      { es: "hoy", en: "today", pron: "oy" },
      { es: "mañana", en: "tomorrow", pron: "mah-NYAH-nah" },
      { es: "ayer", en: "yesterday", pron: "ah-YER" },
      { es: "la hora", en: "the hour / time", pron: "lah OH-rah" },
      { es: "¿Qué hora es?", en: "What time is it?", pron: "keh OH-rah es" },
    ],
  },
  {
    id: "family",
    title: "Family & People",
    items: [
      { es: "la familia", en: "the family", pron: "lah fah-MEE-lyah" },
      { es: "la madre / la mamá", en: "mother / mom", pron: "lah MAH-dreh / lah mah-MAH" },
      { es: "el padre / el papá", en: "father / dad", pron: "el PAH-dreh / el pah-PAH" },
      { es: "el hermano", en: "brother", pron: "el er-MAH-noh" },
      { es: "la hermana", en: "sister", pron: "lah er-MAH-nah" },
      { es: "el hijo", en: "son", pron: "el EE-hoh" },
      { es: "la hija", en: "daughter", pron: "lah EE-hah" },
      { es: "el amigo", en: "friend (male)", pron: "el ah-MEE-goh" },
      { es: "la amiga", en: "friend (female)", pron: "lah ah-MEE-gah" },
      { es: "el hombre", en: "man", pron: "el OHM-breh" },
      { es: "la mujer", en: "woman", pron: "lah moo-HER" },
      { es: "el niño / la niña", en: "boy / girl", pron: "el NEE-nyoh / lah NEE-nyah" },
    ],
  },
  {
    id: "food",
    title: "Food & Drink",
    items: [
      { es: "el agua", en: "water", pron: "el AH-gwah" },
      { es: "la leche", en: "milk", pron: "lah LEH-cheh" },
      { es: "el pan", en: "bread", pron: "el pahn" },
      { es: "el café", en: "coffee", pron: "el kah-FEH" },
      { es: "el té", en: "tea", pron: "el teh" },
      { es: "la fruta", en: "fruit", pron: "lah FROO-tah" },
      { es: "la manzana", en: "apple", pron: "lah mahn-SAH-nah" },
      { es: "el plátano / la banana", en: "banana", pron: "el PLAH-tah-noh" },
      { es: "el arroz", en: "rice", pron: "el ah-RROHS" },
      { es: "el pollo", en: "chicken", pron: "el POH-yoh" },
      { es: "la ensalada", en: "salad", pron: "lah en-sah-LAH-dah" },
      { es: "la comida", en: "food / meal", pron: "lah koh-MEE-dah" },
    ],
  },
  {
    id: "places",
    title: "Places & Directions",
    items: [
      { es: "aquí", en: "here", pron: "ah-KEE" },
      { es: "allí", en: "there", pron: "ah-YEE" },
      { es: "la calle", en: "street", pron: "lah KAH-yeh" },
      { es: "el hotel", en: "hotel", pron: "el oh-TEL" },
      { es: "el restaurante", en: "restaurant", pron: "el res-tow-RAHN-teh" },
      { es: "el baño", en: "bathroom", pron: "el BAH-nyoh" },
      { es: "la estación", en: "station", pron: "lah es-tah-SYON" },
      { es: "izquierda", en: "left", pron: "ees-KYER-dah" },
      { es: "derecha", en: "right", pron: "deh-REH-chah" },
      { es: "recto / derecho", en: "straight", pron: "REK-toh / deh-REH-choh" },
      { es: "cerca", en: "near", pron: "SER-kah" },
      { es: "lejos", en: "far", pron: "LEH-hohs" },
    ],
  },
  {
    id: "verbs",
    title: "Common Verbs",
    items: [
      { es: "soy", en: "I am (permanent)", pron: "soy" },
      { es: "estoy", en: "I am (location/state)", pron: "es-TOY" },
      { es: "eres", en: "you are (permanent)", pron: "EH-res" },
      { es: "estás", en: "you are (location/state)", pron: "es-TAHS" },
      { es: "tengo", en: "I have", pron: "TEN-goh" },
      { es: "tienes", en: "you have", pron: "TYEH-nes" },
      { es: "voy", en: "I go", pron: "boy" },
      { es: "vas", en: "you go", pron: "bahs" },
      { es: "quiero", en: "I want", pron: "KYEH-roh" },
      { es: "quieres", en: "you want", pron: "KYEH-res" },
      { es: "como", en: "I eat", pron: "KOH-moh" },
      { es: "bebo", en: "I drink", pron: "BEH-boh" },
      { es: "hablo", en: "I speak", pron: "AH-bloh" },
      { es: "entiendo", en: "I understand", pron: "en-TYEN-doh" },
    ],
  },
];

// Conversation scenarios: two-way scripted dialogues for voice practice.
// speaker "app" lines are spoken by the app (TTS).
// speaker "user" lines are checked against `accepted` (substring match, accent/case-insensitive).
const SCENARIOS = [
  {
    id: "meeting",
    title: "Meeting Someone New",
    themes: ["greetings"],
    lines: [
      { speaker: "app", text: "¡Hola! ¿Cómo estás?", en: "Hi! How are you?" },
      {
        speaker: "user",
        accepted: ["bien"],
        hint: "Say: Bien, gracias (I'm fine, thanks)",
      },
      { speaker: "app", text: "¡Qué bueno! ¿Cómo te llamas?", en: "Great! What's your name?" },
      {
        speaker: "user",
        accepted: ["me llamo", "mi nombre es"],
        hint: "Say: Me llamo… followed by your name",
      },
      { speaker: "app", text: "¡Mucho gusto!", en: "Nice to meet you!" },
      {
        speaker: "user",
        accepted: ["mucho gusto", "igualmente"],
        hint: "Say: Mucho gusto or Igualmente (likewise)",
      },
      { speaker: "app", text: "¡Adiós! ¡Hasta luego!", en: "Bye! See you later!" },
      {
        speaker: "user",
        accepted: ["adios", "hasta luego"],
        hint: "Say: Adiós",
      },
    ],
  },
  {
    id: "cafe",
    title: "Ordering at a Café",
    themes: ["greetings", "food"],
    lines: [
      { speaker: "app", text: "Buenos días. ¿Qué desea?", en: "Good morning. What would you like?" },
      {
        speaker: "user",
        accepted: ["quiero", "cafe", "agua", "te"],
        hint: "Say: Quiero un café, por favor (I'd like a coffee, please)",
      },
      { speaker: "app", text: "¿Algo más?", en: "Anything else?" },
      {
        speaker: "user",
        accepted: ["no gracias", "no", "nada mas", "si"],
        hint: "Say: No, gracias",
      },
      { speaker: "app", text: "Muy bien. Son dos euros.", en: "Very well. That's two euros." },
      {
        speaker: "user",
        accepted: ["gracias"],
        hint: "Say: Gracias",
      },
      { speaker: "app", text: "¡De nada! ¡Buen provecho!", en: "You're welcome! Enjoy your meal!" },
    ],
  },
  {
    id: "directions",
    title: "Asking for Directions",
    themes: ["places", "verbs"],
    lines: [
      { speaker: "app", text: "Hola, ¿en qué puedo ayudarte?", en: "Hi, how can I help you?" },
      {
        speaker: "user",
        accepted: ["donde esta", "busco"],
        hint: "Say: ¿Dónde está el baño? (Where is the bathroom?)",
      },
      { speaker: "app", text: "Está a la derecha, cerca de aquí.", en: "It's to the right, near here." },
      {
        speaker: "user",
        accepted: ["gracias"],
        hint: "Say: Gracias",
      },
      { speaker: "app", text: "¡De nada! ¡Que tengas un buen día!", en: "You're welcome! Have a good day!" },
    ],
  },
  {
    id: "family-chat",
    title: "Talking About Family",
    themes: ["family", "verbs"],
    lines: [
      { speaker: "app", text: "¿Cuántos hermanos tienes?", en: "How many siblings do you have?" },
      {
        speaker: "user",
        accepted: ["tengo", "no tengo"],
        hint: "Say: Tengo dos hermanos (I have two siblings) or No tengo hermanos",
      },
      { speaker: "app", text: "¿Y tus padres, cómo están?", en: "And your parents, how are they?" },
      {
        speaker: "user",
        accepted: ["bien", "estan bien"],
        hint: "Say: Están bien, gracias",
      },
      { speaker: "app", text: "Me alegro. La familia es importante.", en: "I'm glad. Family is important." },
    ],
  },
  {
    id: "market",
    title: "Shopping for Fruit",
    themes: ["numbers", "food", "colors-days-time"],
    lines: [
      { speaker: "app", text: "Buenos días, ¿qué necesita?", en: "Good morning, what do you need?" },
      {
        speaker: "user",
        accepted: ["quiero", "necesito", "manzanas", "platanos", "fruta"],
        hint: "Say: Quiero manzanas, por favor",
      },
      { speaker: "app", text: "¿Cuántas quiere?", en: "How many would you like?" },
      {
        speaker: "user",
        accepted: ["uno", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", "diez"],
        hint: "Say a number, like Cinco (five)",
      },
      { speaker: "app", text: "Aquí tiene. Son tres euros.", en: "Here you go. That's three euros." },
      {
        speaker: "user",
        accepted: ["gracias"],
        hint: "Say: Gracias",
      },
      { speaker: "app", text: "¡De nada! ¡Adiós!", en: "You're welcome! Bye!" },
    ],
  },
];
